### ISSUE TITLE
Pcap field bit 15

### ISSUE THREAD

**Issue by boxerab** [aous72/OpenJPH#10]
This line:

`        Pcap = 0x00020000; //for jph, Pcap^15 must be set`

Here, you are setting 17th bit of Pcap.  

Also, is the Pcap field not 16 bits ?

**Comment by aous72** [comment]
Pcap is 32 bits.  Whenever a Pcap bit is set, a corresponding Ccap field shall be included in the CAP header; Ccap is 16 bits.

Pcap bits are counted from the most significant bit; perhaps, this is due to the big-endianness.  For HTJ2K, Pcap^15 should be set.  Perhaps the comment can be improved by saying "for jph, Pcap^15 must be set; the 15th MSB bit." I know this might seem weird, but this is how it is.

Cheers,
Aous

**Comment by boxerab** [comment]
Thanks, Aous. Yes, it is weird :) It's not clear from the standard that this is the case, and I couldn't find where it specifies that Pcap is 32 bits. Thanks for clarifying this :)

**Comment by boxerab** [comment]
Actually, I still don't think this is correct :) Even if it is big endian, the 15th MSB bit set should be
`0x00008000` rather than `0x00020000` which is the 17th MSB.

**Comment by aous72** [comment]
Pcap is not in the original Part 1.  It was added later.  It is in the latest addition of Part 1.

The attached picture should make it clear; Pcap<sup>15</sup> indicates JPH -- Perhaps describing it as 15th MSB is still not very clear.
![Screen Shot 2019-12-27 at 11 28 58 am](https://user-images.githubusercontent.com/7401883/71494615-833c5580-289c-11ea-9919-11e94d93fe48.png)

It is weird because it is counted from the MSB, and because it starts with 1, not 0.
Cheers,
Aous.

**Comment by boxerab** [comment]
Alright, I *think* I understand :) , but yes, I find this unusual. 
Thanks,
Aaron
