### ISSUE TITLE
Can the library be compiled on ARM?

### ISSUE THREAD

**Issue by mtisz** [aous72/OpenJPH#18]
Hello,

Thanks for the awesome work! Can this library be compiled on ARM architectures? If so, could you please share a sample makefile?

Thanks!

**Comment by aous72** [comment]
Hi,

Good question.

Yes, the library can be compiled on ARM, but requires a change to the CMakeLists.txt.  I am including a modified [CMakeLists.txt](https://github.com/aous72/OpenJPH/files/4196436/CMakeLists.txt).

Replace the CMakeLists.txt file in OpenJPH/, with this [CMakeLists.txt](https://github.com/aous72/OpenJPH/files/4196436/CMakeLists.txt).

Then, 
```bash
    cd build
    cmake -DCMAKE_BUILD_TYPE=Release -DOJPH_DISABLE_INTEL_SIMD=ON ../
    make
```
This disables the use of Intel SIMD instruction, and the code can be compiled for ARM.

I want to test this new CMakeLists.txt file in Windows before pushing it to repository.

I do not have an ARM machine to test one.  So, I tested the code using QEMU for aarch64 architecture assuming a Cortex-A57.  Because the ARM platform is emulated, the whole process was slow, but the code is working as far as I can tell.

Perhaps you can let us know what platform you use, and advise me what tools to use testing.

Cheers,
Aous.

P.S.: cmake generates a Makefile for you.  I hope this is not an issue.

**Comment by aous72** [comment]
CMakeLists.txt has been integrated into master branch.
