### ISSUE TITLE
ojph_compress fails with README.md command line example for YUV

### ISSUE THREAD

**Issue by NEOAdvancedTechnology** [aous72/OpenJPH#21]
I replicated the README.md example line for YUV input file, and get an error:

```
./ojph_compress -i input_file.yuv -o output_file.j2c -num_decomps 5 -reversible true -dims {3840,2160} -num_comps 3 -signed false -bit_depth 10 -downsamp {1,1},{2,2}

size must start with {
```

This is on Ubuntu 18.04.2 LTS.

**Comment by aous72** [comment]
On Linux and MacOS, bit not Windows, { and } need to be escaped, writing \{ and \}.

So that command line becomes
./ojph_compress -i input_file.yuv -o output_file.j2c -num_decomps 5 -reversible true -dims \{3840,2160\} -num_comps 3 -signed false -bit_depth 10 -downsamp \{1,1\},\{2,2\}

Perhaps I should add a note to README.md.

**Comment by aous72** [comment]
The markdown interpreter remove the escape character.  So I edited my previous comment.

**Comment by NEOAdvancedTechnology** [comment]
Aha, thanks!
