### ISSUE TITLE
Part 15 conformance test files

### ISSUE THREAD

**Issue by boxerab** [aous72/OpenJPH#25]
Hi Aous,
Do you know when part 15 conformance files will be made available? I saw this mentioned, but I can't seem to find any files yet.
Thanks!
Aaron

**Comment by aous72** [comment]
Hi Aaron,

They are not available to public, I believe, but I have access to them.

The problem is that most of them have options that I do not support; examples include region of interest coding, more than 3 coding passes (which is possible), change of progression order, etc.  Many of them were obtained by transcoding from conventional JPEG2000 (JPEG2000 Part1, Part2?).  For this reason, I did not test against them.

Cheers,
Aous.

**Comment by boxerab** [comment]
Thanks, Aous, that makes sense.
