### ISSUE TITLE
precinct::scratch is static and remains dirty after codestream::read() causing crashes

### ISSUE THREAD

**Issue by dtatut** [aous72/OpenJPH#28]
Hi Aous,

while checking playing with the OpenJPH library, it appeared that

precinct::scratch

is static in ojph_codestream.cpp and remains dirty after codestream::read() is called. This causes crashes in a situtation where a codestream is created/read/closed multiple times.

Any reason for having precinct::scratch as static and not cleaning it?

**Comment by aous72** [comment]
Hi Dan,

Thank you for letting me know about an issue.

I did not test reusing an object; I assumed that the codestream object will created again it we wanted to open a new codestream.  

When I wrote the code I tried to minimize the number of memory allocations/de-allocations, as these consume time and has variable latency.

I need to test with your usage scenario, but if the crash is happening due to scratch, I suspect that the subsequent codestream that is causing the crash has different precinct sizes than the first codestream, and therefore needs larger scratch buffer.  

The scratch field is created once in resolution::finalize_alloc, and then set in precinct::parse or precinct::prepare_precinct.

Did I understood things correctly?

Kind regards,
Aous.

**Comment by dtatut** [comment]
Hi Aous,

Well, the problem seems to happen even when using the same codestream. Repeating the following code multiple times causes the problem:

```
for (int i=0; i < someNumberGreaterThanOne; i++)
{
  ojph::j2c_infile j2c_file;
  j2c_file.open("myPicture.jht");
  ojph::codestream codestream;

  codestream.read_headers(&j2c_file);
  ojph::param_siz siz = codestream.access_siz();

  // the following call will crash after the first pass 
  // due to precinct::scratch being initialized with an invalid pointer
  codestream.create();

  codestream.close();
}
```

I hope that helps

Best,
Dan

**Comment by aous72** [comment]
Hi Dan,

Thank you for taking the time to put in an example. 
This is very useful.  I can see the problem now.

I wanted to have one scratch only, something like a singleton.  This should be sufficient for single core processing.
I think I will make a member in the codestream class.

Kind regards,
Aous.
