### ISSUE TITLE
decode: out of bounds buffer access

### ISSUE THREAD

**Issue by boxerab** [aous72/OpenJPH#30]
Hi Aous,
Hope you're keeping well. Using `valgrind`, I found an issue in this code:

```
    inline void rev_read(rev_struct *vlcp)
    {
      //process 4 bytes at a time
      if (vlcp->bits > 32)
        return;
      ui32 val;
      val = *(ui32*)vlcp->data;
      vlcp->data -= 4;
```

`vlcp->size` may be less than 4, in which case the function is accessing out of bounds memory.
You can see this with [this image](https://github.com/uclouvain/openjpeg-data/blob/master/input/nonregression/Bretagne2.ppm) if is is compressed and then decompressed. 
One possible solution is to allocate a few more bytes for `vlcp->data` to avoid this.

Best,
Aaron

**Comment by aous72** [comment]
Hi Aaron,

Thank you for putting this in.  Yes, it can happen.

The cleanup pass of a HTJ2K codeblock is made up of three sections; in order, they are: the magnitude-sign (MagSgn) section, which is read from the first byte going forward;  the MEL section, which is also read forward; and the VLC section, which is read from the last byte going backward.

For convenience, here we read 4 bytes at a time from the VLC section.  So if the MagSgn and MEL are short (the MEL section can have 0 bytes), there is the possibility that when we reading from the VLC section, we read from before the first byte of the MagSgn section (i.e., from before the first byte in the codeblock).

This needs to be fixed. Let's keep this issue open until I fix it.

Thank you again.

Kind regards,
Aous.

**Comment by boxerab** [comment]
Great, thanks for the explanation, and for looking into this.

**Comment by aous72** [comment]
Hi Aaron,

I should have come earlier, but my head is in another project.

I added 8 bytes in front of the buffer.  If vlcp->size becomes smaller than -8, an error message will terminate the code.  There is an additional 24 bytes of memory before the vlcp->buf field, which are used to store information about the buffer size and the likes; have a look at 'struct coded_lists' in ojph_mem.h if you like.

I could not replicate the issue with valgrind (this is the first time I use it), but since I knew about the possibility, I added the extra space, in addition to the existing 24 bytes.  In any case, the code should not read from these 24 bytes.

It can useful to replicate the issue you faced.  The bug might be somewhere else.  I need more details, so if you have the time, please provide more details.  You linked the original ppm file, but I am not very sure what options were used with it.  I am also not very sure what options were given to valgrind.

While fiddling with valgrind, I discovered a bug in the encoder, which I totally overlooked in the past.  I think I need to add valgrind to the necessary tools in my repertoire.

Thank you for all your help.

Kind regards,
Aous.

**Comment by boxerab** [comment]
Hi Aous,
Thanks a lot for these fixes. Yes, valgrind is a fantastic tool to have in your toolkit.
I will do some more testing, and share the settings I used.
Best,
Aaron

**Comment by boxerab** [comment]
I haven't found any valgrind errors in a while. Closing.
