### ISSUE TITLE
block coder/decoder: add more comments to the code ?

### ISSUE THREAD

**Issue by boxerab** [aous72/OpenJPH#42]
Hi Aous,
Hope all is well. I am really interested in getting a better understanding
of how the block coder and decoder work. I have a copy of the Part 15 draft, but if
you have a little time to add comments here and there to the block coder, it would help 
me parse it. 
Thanks!
Aaron

**Comment by aous72** [comment]
Hi Aaron,

All is good; thank you for asking.  I hope you are well.

I will do that before next week.  I am happy to help with this.

I think one thing that is not very clear in the standard is the following:
If we represent wavelet coefficient by μ for the magnitude and and s for the sign, where s is either 0 (for positive) or 1 (for negative); then, the encoder encodes 2 (μ - 1) + s values.  I hope this helps.

Cheers,
Aous.

**Comment by aous72** [comment]
Another opensource implementation, which is written in Matlab, is:
https://github.com/osamu620/MatHTJ2K
I will add a fork of this to me repositories.

**Comment by boxerab** [comment]
> Hi Aaron,
> 
> All is good; thank you for asking. I hope you are well.
> 
> I will do that before next week. I am happy to help with this.
> 
> I think one thing that is not very clear in the standard is the following:
> If we represent wavelet coefficient by μ for the magnitude and and s for the sign, where s is either 0 (for positive) or 1 (for negative); then, the encoder encodes 2 (μ - 1) + s values. I hope this helps.
> 
> Cheers,
> Aous.

Thanks, Aous. Any guidance you can add to the code would be a great help.
Aaron

**Comment by aous72** [comment]
Hi Aaron,

I managed to document the decoder.  Unfortunately I could not document the encoder as well; I am hoping to get this one by the end of this week (1st of Nov).

I am including the decoder here for your reference; I had to change the extension to .txt in order to upload it.  I will commit it with the rest of the code with my new release.

It was good to document that the code since this helped me uncover potential issues. If there any issues I will address them in a future commit.

I am in the process of developing a test for my library; this is currently in my development branch.  This is needed because I made a lot of changes in my code in the process of reducing sign-unsigned warnings.

Cheers,
Aous.

[ojph_block_decoder.txt](https://github.com/aous72/OpenJPH/files/5434685/ojph_block_decoder.txt)

**Comment by boxerab** [comment]
Fantastic! Thank you very much. I also find that documenting an algorithm helps improve the code itself when I think about possible edge cases.  But it needs enough time and the right frame of mind to do it.
I'm glad to hear about the test framework, then you can refactor the code with peace of mind that you aren't breaking things.  I would also recommend applying to [oss-fuzz](https://github.com/google/oss-fuzz), particularly for the decoder, as it will uncover bugs.

**Comment by boxerab** [comment]
Thanks, going to close this now.
