### ISSUE TITLE
decoder: rev_init potential underflow

### ISSUE THREAD

**Issue by boxerab** [aous72/OpenJPH#45]
Hi Aous,
Another question: in the `rev_init` decoder method,  `vlcp->data` is decremented by
`(tnum+3)` bytes, but `vlcp->size` is not decremented by the same amount. Is it then
possible to get an underflow ?
Thanks,
Aaron

**Comment by aous72** [comment]
Hi Aaron,

Thank you for looking into the code.  This issue is hard to spot.

I agree we need to subtract tnum from the size.  But this 3 serves another issue.  The simplest solution is use this code:

```c++
    inline void rev_init(rev_struct *vlcp, ui8* data, int lcup, int scup)
    {
      //first byte has only the upper 4 bits
      vlcp->data = data + lcup - 2;

      //size can not be larger than this, in fact it should be smaller
      vlcp->size = scup - 2;

      ui32 d = *vlcp->data--;
      vlcp->tmp = d >> 4; //both initialize and set
      vlcp->bits = 4 - ((vlcp->tmp & 7) == 7);
      vlcp->unstuff = (d | 0xF) > 0x8F;

      vlcp->data -= 3; //make ready to read a 32 bits
      rev_read(vlcp);
    }
```

The -3 moves the pointer to a position where the next read is a 32 bit read, there is no data consumed here.  This made unusual (at least to me) because the bitstream is read backward.
To see this consider the following data arrangement
```
 5   4   3   2   1
UU  UU  UU  UU  UU  XF FF
```
where the U is unread, X is read, and FFF are the last bits in the bitstream that contain the length of MEL+VLC (see the standard).
After reading X in "ui32 d = *vlcp->data--;" the data pointer is moved to location 1, then we subtract 3, making it more to location 4.  When we read 32 bits, locations 1 to 4 are read. So no data is lost.

One can also replace "ui32 d = *vlcp->data--;" with "ui32 d = *vlcp->data;" and then subtract 4; this is perhaps the clearest option. Alternatively, one can have an initialization code without any subtractions, but then we have to move the pointer backward before every data reading.  You might prefer this option.

The reason for the extra for loop is to align the read address to a multiple of 4 (i.e., aligned 32bit reads), which is a requirement for the CUDA code I was developing, on which some of this code is based.  Unaligned 32 bit reads are not an issue for ARM or Intel-based architectures, and therefore we can write a simpler code.

Let me know what you think.

Kind regards,
Aous.

**Comment by boxerab** [comment]
Hi Aous,

> One can also replace "ui32 d = *vlcp->data--;" with "ui32 d = *vlcp->data;" and then subtract 4; this is perhaps the clearest option.

Thank you for the explanation of the code. I like this approach, as it is clearer what is happening in the code. 

As for the alignment code, could this be left in with a comment about why it is needed for GPU alignment? And also
decrementing size by tnum ?

Thanks,
Aaron

**Comment by boxerab** [comment]
Thanks, Aous, this is now resolved. Closing.
