### ISSUE TITLE
New library htjpeg2000

### ISSUE THREAD

**Issue by Jamaika1** [aous72/OpenJPH#63]
A new jpeg2000 library has appeared on the official pages. Too bad there are no part16 and part17 parts included. ;)
https://gitlab.com/wg1/htj2k-rs

**Comment by osamu620** [comment]
@Jamaika1 htj2k-rs has been developed as the reference software of HTJ2K. Another implementation is also available at https://github.com/osamu620/OpenHTJ2K. It is confirmed that both implementations pass the conformance testing defined in JPEG 2000 Part 4. OpenJPH is a great library, however, passing the test has not done because decoding codestreams with some of the optional marker codes (i.e. COC, QCC, POC) are not supported yet :)

**Comment by osamu620** [comment]
@malaterre From the performance (encoding/decoding speed) point of view, OpenHTJ2K outperforms htj2k-rs. Also, I believe openjpeg is now capable to handle htj2k codestreams and @aous72 can say more about the status of htj2k in openjpeg.

**Comment by aous72** [comment]
@malaterre 
Thank you for your interest. Adding a package for HTJ2K would be great.

I agree with @osamu620  statement.

These are my thoughts.
- I developed OpenJPH with idea of making it fast, with support to most widely used features of HTJ2K.  You may notice some unusual approach to memory allocation/de-allocation. I got bogged down with other tasks, and I have not had the time to continue developing it, but I intend to do so at some point.  Many things can be done to improve its performance/compliance.
- Osamu developed his OpenHTJ2K to be more compliant with the features of J2K and HTJ2K, and it can pass all conformance tests, AFAIK.  With help from @boxerab, multithreading has been added to OpenHTJ2K, perhaps other features.
- I was later asked if I can add HTJ2K DECODING to OpenJPEG.  So that work produced https://github.com/uclouvain/openjpeg/pull/1381.  This is part of version 2.5.0dev. The text details what is missing in that decoding implementation -- I suspect the missing features would not be widely used, but I can be wrong.

Hope this helps.  Let us know if we can be of further assistance.

Cheers,
Aous

**Comment by boxerab** [comment]
> Edit: OpenJPH does not support multithreading yet, although @boxerab attempted to have this added -- thank you Aaron, and sorry for the disappointment. I think multithreading should only be added once the encoder/decoder is optimized, as optimizing the decoder can improve speed enormously, making simple multithreading designs not very useful.

@aous72 you're welcome, I know you will consider this feature when you are ready :)  I am very much looking forward to when you have time to optimise the encoder/decoder.
